### ISSUE TITLE
Scalar type for json/jsonb

### ISSUE THREAD

**Issue by bkniffler** [babyfish-ct/graphql-ts-client#1]
Hi, really cool framework! How can we handle types like json/jsonb that e.g. Hasura uses? Its neither scalar string nor number or boolean, its just a pure JSON value (so Record<string, unknown/any>).

**Comment by babyfish-ct** [comment]
All the basic types such as string, number, enum is called scalar type in GraphQL

Fortunately, scalar type is extendable for GraphQL. you must do two works

1. Extend the scalar type of server-side, many frameworks of GraphQL server-side support API to extend scalar type, you can use that API to teach the GraphQL server how to accept your customize scalar type

2. We your schema contains the customized scalar type and the code generator of my framework try to generate TS code from it. Be same with the server-side, your must call my API to teach my framework about how to accept your customize type. please use the configuration property "scalarTypeMap" of code generator. document here: https://github.com/babyfish-ct/graphql-ts-client/blob/master/codegen-properties.md

**Comment by bkniffler** [comment]
Hey @babyfish-ct, thanks for taking the time to respond. But how would the `scalarTypeMap` field look like in that case? 

<img width="536" alt="Bildschirmfoto 2021-08-19 um 15 30 02" src="https://user-images.githubusercontent.com/4349324/130077157-80e60922-e000-4972-bb87-88d056240499.png">

Wouldn't it make sense to add all graphql value kinds (as specified in https://github.com/graphql/graphql-js/blob/c589c3d285cb1ec44b09bf0b50ec041ec083760c/src/language/kinds.ts#L21)?

**Comment by bkniffler** [comment]
<img width="795" alt="Bildschirmfoto 2021-08-19 um 16 16 17" src="https://user-images.githubusercontent.com/4349324/130084562-8c9dd439-dfa2-47a1-90c5-62457abaf292.png">

Seems to work good if this is commented out. So maybe just adding `object` besides other scalars would work.

**Comment by babyfish-ct** [comment]
This solution is conflict with GraphQL

In GraphQL, complex object must object, server-side will check the shape of response data. so it's impossible let server to return a response data contains a field whose type is scalar but actually contains deeper child fields.

Make the field to be string, serialize/deserialize it in your app please

**Comment by hcharley** [comment]
@babyfish-ct If GraphQL implementations allow for object types, why not support it with this library?

I am just trying out this library for the first time today, and I'm concerned that if I have to change my JSON types to strings, I might just end up not using or having to fork the library.

**Comment by VojtaStanek** [comment]
> so it's impossible let server to return a response data contains a field whose type is scalar but actually contains deeper child fields.

I agree it's not a best practice, but sometimes the data doesn't have a defined shape, so JSON is a reasonable choice. There are servers which return such data and we have to handle it somehow.

**Comment by babyfish-ct** [comment]
The big problem is how to import custom scalar type

**Comment by babyfish-ct** [comment]
3.1.0
