### ISSUE TITLE
Cannot stringify nested input arguments

### ISSUE THREAD

**Issue by VojtaStanek** [babyfish-ct/graphql-ts-client#14]
This code:

```
execute(mutation$.upsertIssue(
	{
		by: {
			year: 2022,
			issue: 19,
		},
		create: {
			title: "A",
			subtitle: "B",
		},
		update: {
			title: "A",
			subtitle: "B",
		},
	},
	issueUpsertResult$.ok.errorMessage,
))
```

Results in the following query

```
mutation {
        upsertIssue(
                by: ,
                "year": 2022,
                "issue": 19,
                create: ,
                "title": "A",
                "subtitle": "B",
                update: ,
                "title": "A",
                "subtitle": "B"
        ) {
                ok
                errorMessage
        }
}
```

Expected mutation:
```
mutation {
        upsertIssue(
                by: { "year": 2022, "issue": 19 },
                create: { "title": "A", "subtitle": "B" },
                update: { "title": "A", "subtitle": "B" },
        ) {
                ok
                errorMessage
        }
}
```

**Comment by babyfish-ct** [comment]
![image](https://user-images.githubusercontent.com/15168900/167848271-bddf398d-3b74-409e-ad9a-2671632a6e24.png)

I tested, cannot reproduce.

**Comment by babyfish-ct** [comment]
I reproduced. 

This is a bug, although it's not recommended style: hard code style.
`execute(mutation$.doSomething({...blalba...}, fetcher));`

You should use the more recommended code: parameterized style
`execute(
        mutation$.doSomething(fetcher), 
        { variables: {...blalba...} }
);`

Parameterized style can run successful, so you can continue your job. In fact you should always use parameterized style.

Even if I fix this bug in the future to make hardcoded style can work, please don't use the hardcoded style.

**Comment by babyfish-ct** [comment]
3.0.17 is released.

You can use hardcode style code to validate it again. If it works, please close this issue.

Remember, even if this issue has been resolved, please don't use hardcode style in your real projects.

**Comment by VojtaStanek** [comment]
This works very well! Thanks a lot for the quick response!
