### ISSUE TITLE
Using alias for the same field, includes only the last field in the query

### ISSUE THREAD

**Issue by RestinGreen** [babyfish-ct/graphql-ts-client#19]
Hello. I cloned the example repo and was able to replicate it.

Just went into the EmployeeList.tsx file and as a test added these rows:

`const test = query$
.findEmployees(employeeConnection$.totalCount, option => option.alias("first"))
.findEmployees(employeeConnection$.totalCount, option => option.alias("second"))
.findEmployees(employeeConnection$.totalCount, option => option.alias("third"))
console.log(test.toString())`

Expected output of the console log is:
![image](https://user-images.githubusercontent.com/18681702/175119114-99f87620-9ef6-4b03-b6ba-3e493f91818d.png)

But I get 
![image](https://user-images.githubusercontent.com/18681702/175119844-c132f692-422b-4e6b-a17e-36cd7d23125d.png)
The aliases "first" and "second" didn't show up in the query.

Is this an issue on the way I construct the query or a bug?
If i try it in GraphiQl, the expected syntax is correct.

**Comment by babyfish-ct** [comment]
Hi RestinGreen

Please use v3.1.7 to validate it, if no problem, please close it

**Comment by RestinGreen** [comment]
In the meantime 3.1.8 was out and i tested it with that version.
The bug is fixed. 

Thank you! Closing it.
