### ISSUE TITLE
Feature: more types of enum generation

### ISSUE THREAD

**Issue by robsonfj** [babyfish-ct/graphql-ts-client#29]
The tsEnum option could have another option to generate enum types with string values

Currently with tsEnum=true generates:
`enum  Count {
 ONE, TWO, THREE
}`

i would like to keep my values as strings, but still generating enum types instead of union types like this:
`type Count = 'ONE' | 'TWO' | 'THREE'`

Support for enum types with value strings like this would be nice :+1: :
```
enum Count {
   ONE = 'ONE', 
   TWO = 'TWO',
   THREE = 'THREE'
}
```

**Comment by robsonfj** [comment]
I ended up adding this to the code, https://github.com/babyfish-ct/graphql-ts-client/pull/32

**Comment by babyfish-ct** [comment]
Generating ts-only enun type is the design of older version, the current version is generating union type.

That's because union type is used by js ecosystem before ts was created. it is too popular.
