### ISSUE TITLE
How do i execute a subscription?

### ISSUE THREAD

**Issue by IceBlizz6** [babyfish-ct/graphql-ts-client#31]
I'm not able to figure out how to execute subscriptions,
and i can't find this in the documentation either.

Is anyone able to give a code sample?
And maybe it could be added to the documentation too.

**Comment by babyfish-ct** [comment]
Unfortunately, this library does not support subscriptions.

**Comment by IceBlizz6** [comment]
I'm sorry to hear that.
But thank you for taking the time to respond to my question.
