### ISSUE TITLE
Type of filter for nullable field is possibly wrong

### ISSUE THREAD

**Issue by Miladiir** [babyfish-ct/graphql-ts-client#4]
你好!
谢谢你 for the library. It has been a joy to use so far.

One thing I noticed is that the types for a filter whose type is nullable, for example String as opposed to String!, are possible broken.

For example, lets say I have a field called email with type String and a filter called equals exist for that field. In a graphql PlayGround I can type this query as 
```
query usersWithNoEmail() {
  users( where: { email: { equals: null } }){
    id,
    userName,
    email
}
```

And as I would expect I get a response that looks something like: 
```
{
  "data": {
    "users":  [
        {
        "id": "1234",
        "userName":  "testUser",
        "email": null
        },
        ....
      ]
   }
}
```

However, the generated type for the filter looks something like this:
```
...
email?: { equals?: string | undefined , ...}
...
```

I believe this is incorrect. If I pass undefined as opposed to null as a value, that part of the filter is simply discarded. When I strictly follow the generated type it seems it is not possible for me to filter using null values.

My backend supports this, of course, so when I simply ignore the generated type with a `// @ts-ignore`, the query is executed as expected.

Is it possible that there is a setting that I missed? My config looks something like this:

```
const {
  ApolloGenerator,
  loadRemoteSchema,
} = require("graphql-ts-client-codegen");
const path = require("path");
const generator = new ApolloGenerator({
  schemaLoader: async () => {
    return loadRemoteSchema(REDACTED);
  },
  targetDir: path.join(__dirname, "../src/__generated"),
  defaultFetcherExcludeMap: {},
  scalarTypeMap: {
    Decimal: "number",
  },
});
generator.generate();

```

**Comment by babyfish-ct** [comment]
Thanks for reminding me that I forgot to write it in the document

For a long time, null and undefined make the development of JS/TS into trouble. The graphql-ts-client and graphql-state try to end this situation, **eliminate null, all unified into undefined** (for TypeScript, undefined is a better choice)

Please use conditions like this
```
Where: {email: {equal to: undefined}}
```

Not only for case of input, but also for case of output. When you receive data from the server, the raw data returned by the server has null values, but you will find that the result you received does not have null values. You can try :)

**Comment by Miladiir** [comment]
When I fire a query with `...({ where: { email: { equals: undefined } } }) ` as suggested I see in the network traffic, that the actual request to the server is
```
{
  "where": {
    "email": {}
  }
}
```

Which semantically is equal to just ommiting a filter. What I am explicitly trying to do is filter for values where the entry in the database is NULL. My backend graphql server has the ability to perform this query with:
```
{
  "where": {
    "email": { "equals": null}
  }
}
```

which I could get by `...({ where: { email: { equals: null } }) `.
For that I currently ignore the typescript error.

I understand what you are trying to do and I too prefer to not mix usage of undefined and null, but in this specific case `null` is needed to perform the correct query.

One possible solution is to allow null as an input in `where` or to handle undefined and optional differently, e.g.
```
typescript -> generated graphql query
({ where: { email: { equals: undefined} }) -> {"where": {"email": { "equals": null}  } }

({ where: { email: { }) -> {"where": {"email": {}  } }
```

I will try to setup a reproducible environment, so I can show the problem to you better. I think it is just getting lost in the words, but when you see it you will immediatly understand or possibly know of a workaround.

Again, many thanks for the library and your fast response!

**Comment by babyfish-ct** [comment]
I understand your problem, some server only accept null argument, you input type need support null

**Comment by babyfish-ct** [comment]
Ok, Now I'm writing document for "graphql-state". I will do this tiny change after document work of "graphql-state".

Now, you can uses this work around, it can successfully work

```
const name: string | null = ....;

...{name: name as string | undefined} // force cast "string | null" to "string | undefined"
```
