### ISSUE TITLE
Uncaught Error: Illegal fetchable type "CustomerData", super class can only be specified for object type but its category is "EMBEDDED"

### ISSUE THREAD

**Issue by wedreamer** [babyfish-ct/graphql-ts-client#5]
### code gen script

```ts
import { ApolloGenerator, loadRemoteSchema } from 'graphql-ts-client-codegen';
import { join } from 'path';

// https://github.com/babyfish-ct/graphql-ts-client/blob/master/doc/apollo_zh_CN.md
const generator = new ApolloGenerator({
  schemaLoader: async () => {
    return loadRemoteSchema(
      'https://ininderprint-backend-nestjs.cloud-dev.ininderprint.tw/vendor-api/graphql'
    );
  },
  targetDir: join(__dirname, '../src/gencode') as string,
  defaultFetcherExcludeMap: {
    // Department: ['avgSalary'],
  },
  scalarTypeMap: {
    String: 'string',
  },
});
generator.generate();
```

### graphql req file
```tsx
import { useTypedQuery } from 'gencode';
import { query$, userProfile$ } from 'gencode/fetchers';
import React from 'react';

export default function Orders() {
  const { data, loading, error } = useTypedQuery(
    query$.myProfile(
      userProfile$.userUuid.nickname.firstName.lastName.gender.birthday.avatar
    )
  );

  return (
    <>
      {loading && <div style={{ color: 'green' }}>Loading...</div>}
      {error && <div style={{ color: 'red' }}>Error</div>}
      <div>userUuid: {data?.myProfile.userUuid}</div>
      <div>userUuid: {data?.myProfile.nickname}</div>
      <div>userUuid: {data?.myProfile.firstName}</div>
      <div>userUuid: {data?.myProfile.lastName}</div>
      <div>userUuid: {data?.myProfile.gender}</div>
      <div>userUuid: {data?.myProfile.birthday}</div>
      <div>userUuid: {data?.myProfile.avatar}</div>
    </>
  );
}
```
### screenshot relate info

![oThG11.md.png](https://shubuzuo.aiur.site/clipboardimg_1639159109781.png)

![oThyct.md.png](https://shubuzuo.aiur.site/clipboardimg_1639159119278.png)

![oThfAg.md.png](https://shubuzuo.aiur.site/clipboardimg_1639159129461.png)

Trouble brother，Thank you very much and good luck

**Comment by wedreamer** [comment]
![detail error](https://kahla-user-files.aiur.site/conversation-87/2021-12-10/clipboardimg_1639163881002.png?token=eyJzaXRlTmFtZSI6ImthaGxhLXVzZXItZmlsZXMiLCJ1bmRlclBhdGgiOiJjb252ZXJzYXRpb24tODciLCJwZXJtaXNzaW9ucyI6IkRvd25sb2FkIiwiZXhwaXJlcyI6IjIwMjEtMTItMTBUMjA6MTc6NTcuOTcwMjYyNFoifQ%3D%3D.lQeivOXk1kKJX6X%2FIPjIUocUuDFV6u1fIs%2Fcpjnf%2BXtYp0DQVeuJo%2F%2FO%2F4JhWWLhUWWX0pH2xY40GVSf%2BIDfAYdJEfFcO6thaoR37tgxgDVerAwLMi63eN6oukRvzYsAepgBEnN6zVU0sJHv7AgwDwsmUeqCfEnH4P%2BgcjgSCXE%3D)

**Comment by babyfish-ct** [comment]
Give me your SDL please

BTW, your fetcher is to longer, you can try to use the default fetcher "userProfile$$"

**Comment by wedreamer** [comment]
> 

this is my point https://ininderprint-backend-nestjs.cloud-dev.ininderprint.tw/vendor-api/graphql

i try use "userProfile$$" which also ，i also try add your wechat [看]

**Comment by wedreamer** [comment]
Can we communicate directly by video, this is too inefficient

**Comment by wedreamer** [comment]
With the help of the author, the related problem was found, and the corresponding update is in v3.0.9，The document is related to [doc](https://github.com/babyfish-ct/graphql-ts-client/blob/master/doc/fetcher/fragment.md), the reason is **my graphql type has union type and this dont have ID **。
