### ISSUE TITLE
Annotation Support 

### ISSUE THREAD

**Issue by Wallacy** [babyfish-ct/graphql-ts-client#8]
Will be nice if we can support the annotations (Like Deprecation that is inserted as comment) like `graphql-code-generator` does!

Anyway, awesome job!

**Comment by babyfish-ct** [comment]
Do you means the directives?
If yes, please visit https://github.com/babyfish-ct/graphql-ts-client/blob/master/doc/fetcher/directive.md
If not, would please describe it more clearly?

**Comment by babyfish-ct** [comment]
got it

**Comment by babyfish-ct** [comment]
Now, 3.0.11 can resolve it. (codegen is changed, api is not changed)

----------------------------------

Sorry for making you wait a while, as this little issue is not a high priority.

During this time, I am working hard on two new projects
1. https://github.com/babyfish-ct/kimmer
2. https://github.com/babyfish-ct/graphql-provider

graphql-provider is a GRM *(GraphQL relation mapping)*, which is very similar to ORM, allowing users to quickly build a GraphQL server based on RBBMS (using kotlin and R2DBC)

**Comment by babyfish-ct** [comment]
Wait for your validation, if it works in your app, please close this issue.

**Comment by Wallacy** [comment]
Hello! Sorry, i just saw the notification today. I will ;) Thanks!!

**Comment by Wallacy** [comment]
@babyfish-ct Sorry, did not make any diference :(

**Comment by babyfish-ct** [comment]
Yes, "isDeprecated" is deleted since graphql 16, only "depcreatedReason" can be used.

Please try 3.0.12

**Comment by Wallacy** [comment]
Hello @babyfish-ct ,

Worked on the last commit. But the npm version has the old code ;)

**Comment by babyfish-ct** [comment]
3.0.13

**Comment by Wallacy** [comment]
Thanks!!!
